version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-teste
    restart: always
    environment:
      POSTGRES_DB: db_prisma_teste
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

